openapi: 3.0.2
info:
    title: OpenAPI definition
    description: Manages ToDO list tasks
    version: 0.1.0
servers:
    - url: http://localhost:8000/todolist/api
paths:
    /tasks:
        get:
        post:
    /tasks/{taskId}:
        get:
        put:
        delete:
