openapi: 3.0.2
info:
    title: OpenAPI definition
    description: Manages ToDO list tasks
    version: 0.1.0
paths:
    /users:
        get:
            summary: List users
            description: Returns a list of users
