openapi: 3.0.2
info:
    title: OpenAPI definition
    description: Manages ToDo list tasks
    version: 0.1.0
servers:
    - url: http://localhost:8000/todolist/api
tags:
    - name: Tasks
      description: Manages ToDO list tasks
paths:
    /tasks:
        get:
            tags:
                - Tasks
            description: Gets the information for the specified task
            responses:
                '200':
                    description: All the tasks have been retrieved
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/tasks'
        post:
            tags:
                - Tasks
            description: Creates a new task
            responses:
                '201':
                    description: Task successfully created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/task'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/message'
    /tasks/{taskId}:
        get:
            tags:
                - Tasks
            description: Gets the information for the specified task
            responses:
                '200':
                    description: The task has been successfully retrieved
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/task'
                '404':
                    description: The task was not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/message'
        put:
            tags:
                - Tasks
            description: Updates all the info for a task
            responses:
                '202':
                    description: The task has been successfully updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/task'
                '404':
                    description: The task was not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/message'
        delete:
            tags:
                - Tasks
            description: Deletes a task
            responses:
                '204':
                    description: The task has been successfully deleted
                '404':
                    description: The task was not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/message'
components:
    schemas:
        task:
            type: object
            required:
                - title
                - status
            properties:
                title:
                    type: string
                status:
                    type: string
                    enum: [New, In Progress, Completed]
        tasks:
            type: array
            items:
                $ref: '#/components/schemas/task'
        message:
            type: object
            required:
                - message
            properties:
                message:
                    type: string
